app:
  name: 'auth'
  version: '1.0.0'

http:
  port: '3000'

logger:
  log_level: 'debug'
  rollbar_env: 'auth'


users:
  - name: 'test123'
    password: '$2a$14$ke.euFhogr5WCqXSagVuceiZc2o6w/Z6hoL9KIVqIPZdEZL4TRF9K'
  - name: ''
    password: ''

profile:
  login: 'test123'
  password: 'qwerty'
  enabled: true